In [0]:
!pip install -r requirements.txt

     |████████████████████████████████| 24.2MB 1.4MB/s 
  Found existing installation: gensim 3.6.0
    Uninstalling gensim-3.6.0:
      Successfully uninstalled gensim-3.6.0


In [0]:
import re
import nltk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from gensim.models.phrases import Phrases, Phraser
from TurkishStemmer import TurkishStemmer
from gensim.models import Word2Vec
import multiprocessing
import pandas as pd
import string
pd.options.display.max_colwidth = 8000
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/naynco/nayn.data/master/classification_clean.csv")
df.dropna().reset_index(drop=True)

id  ...                                                                                                          Slug
0          18  ...                                        kuba-milli-takimi-oyuncularinin-bir-kadina-tecavuz-ettigi-iddia-edildi
1          21  ...                              daily-telegraph-suriyelilere-vatandaslik-teklifi-ab-anlasmasini-tehlikeye-atiyor
2          24  ...                                                                       aymden-yuksek-sesli-ezan-sikayetine-ret
3          31  ...                                        istanbuldaki-teror-saldirisi-etoonun-duzenleyecegi-organizasyonu-vurdu
4          34  ...                                       turkiye-rusyadaki-en-populer-destinasyon-liderligini-uc-gunde-geri-aldi
5          37  ...                                turkiyeye-atis-hazirligindaki-68-isid-hedefi-imha-edildi-14-terorist-olduruldu
6          39  ...                                                           sporting-lizbon-hocasi-jesus-podolski-tam-bize-gore
7          40  ...                                                         almanlarda-turkiye-korkusu-yayildi-tatile-gelmiyorlar
8          45  ...                                                              fernandao-sezon-basi-antrenmanina-102-kilo-geldi
9          56  ...                                             erdogandan-rusya-ve-israil-mesaji-kopan-iliskileri-tamir-ediyoruz
10         60  ...                                        taliban-militani-intihar-yelegini-yanlislikla-patlatti-24-militan-oldu
11         61  ...                                     ataturk-havalimanindaki-saldiriyla-ilgili-17-kisinin-tutuklanmasi-istendi
12         62  ...                                                            suriyelilere-vatandaslikta-12b-formulu-isletilecek
13         63  ...                                   emre-morun-menajeri-isid-iddialarini-yapanlarla-kanun-onunde-hesaplasacagiz
14         64  ...                                    sneijder-galatasarayin-kestigi-2-2-milyon-euroluk-ceza-icin-fifaya-gidiyor
15         65  ...                                                            fenerbahce-neustadter-transferini-borsaya-bildirdi
16         67  ...                                        enerji-bakani-sakasi-yok-yatirim-yapilmazsa-istanbul-elektriksiz-kalir
17         78  ...                                                         pyd-es-baskani-rojava-federasyonundan-vazgecmeyecegiz
18         85  ...                                    basbakan-yildirim-suriye-ile-gorusme-sartini-acikladi-once-diktator-gitsin
19         88  ...                                                           besiktas-90-milyon-liralik-borcunun-hepsini-kapatti
20         91  ...                                                      besiktas-mario-gomezin-yerine-mario-mandzukici-dusunuyor
21         94  ...                                                                               stoke-city-nani-ile-ilgileniyor
22         99  ...                                                                      kanada-basbakani-onur-yuruyusunde-yurudu
23        100  ...                                                                        van-damme-hz-muhammed-cok-zeki-biriydi
24        101  ...                                                                  rihanna-virusten-korkunca-konseri-iptal-etti
25        106  ...                                                     medinede-mescid-i-nebi-yakininda-iftar-saatinde-patmalama
26        113  ...                                                         fenerbahce-gregory-van-der-wiel-ile-sozlesme-imzaladi
27        117  ...                                               suudi-arabistanda-duzenlenen-saldirilardan-ilk-goruntuler-geldi
28        130  ...                                             medinedeki-patlamanin-ardindan-olay-yerinden-ilk-goruntuler-video
29        136  ...                                                    nbade-yilin-transferi-kevin-durant-golden-state-warriorsta
...       ..

In [0]:
docs = np.array(df['Title'])
classes = np.array(df['Categories'])
df_docs = pd.DataFrame({'Document': docs, 
                        'Class': classes})
df_docs = df_docs[['Document', 'Class']]
df_docs

Document   Class
0                                            Küba Milli Takımı Oyuncularının, Bir Kadına Tecavüz Ettiği İddia Edildi   SICAK
1                                Daily Telegraph: 'Suriyelilere Vatandaşlık Teklifi AB Anlaşmasını Tehlikeye Atıyor'   SICAK
2                                                                         AYM'den 'Yüksek Sesli Ezan' Şikayetine Ret   SICAK
3                                         İstanbul'daki Terör Saldırısı, Eto'o'nun Düzenleyeceği Organizasyonu Vurdu   SICAK
4                                          Türkiye, Rusya'daki En Popüler Destinasyon Liderliğini Üç Günde Geri Aldı   SICAK
5                                   Türkiye'ye Atış Hazırlığındaki 68 IŞİD Hedefi İmha Edildi! 14 Terörist Öldürüldü   SICAK
6                                                               Sporting Lizbon Hocası Jesus: Podolski Tam Bize Göre   SICAK
7                                                           Almanlarda 'Türkiye' Korkusu Yayıldı, Tatile Gelmiyorlar   SICAK
8                                                                  Fernandao, Sezon Başı Antrenmanına 102 Kilo Geldi   SICAK
9                                                Erdoğan'dan Rusya ve İsrail Mesajı: Kopan İlişkileri Tamir Ediyoruz   SICAK
10                                          Taliban Militanı, İntihar Yeleğini Yanlışlıkla Patlattı; 24 Militan Öldü   SICAK
11                                        Atatürk Havalimanı'ndaki Saldırıyla İlgili 17 Kişinin Tutuklanması İstendi   SICAK
12                                                              Suriyelilere Vatandaşlıkta '12B' Formülü İşletilecek   SICAK
13                                     Emre Mor'un Menajeri: IŞİD İddialarını Yapanlarla Kanun Önünde Hesaplaşacağız   SICAK
14                                    Sneijder, Galatasaray'ın Kestiği 2.2 Milyon Euro'luk Ceza İçin FIFA'ya Gidiyor   SICAK
15                                                               Fenerbahçe, Neustadter Transferini Borsaya Bildirdi   SICAK
16                                          Enerji Bakanı: Şakası Yok! Yatırım Yapılmazsa İstanbul Elektriksiz Kalır   SICAK
17                                                            PYD Eş Başkanı: Rojava Federasyonundan Vazgeçmeyeceğiz   SICAK
18                                      Başbakan Yıldırım, Suriye ile Görüşme Şartını Açıkladı: Önce Diktatör Gitsin   SICAK
19                                                              Beşiktaş, 90 Milyon Liralık Borcunun Hepsini Kapattı   SICAK
20                                                       Beşiktaş, Mario Gomez'in Yerine Mario Mandzukic'i Düşünüyor   SICAK
21                                                                                  Stoke City, Nani ile İlgileniyor   SICAK
22                                                                          KANADA BAŞBAKANI ONUR YÜRÜYÜŞÜNDE YÜRÜDÜ   SICAK
23                                                                          Van Damme: Hz. Muhammed Çok Zeki Biriydi   SICAK
24                                                                     Rihanna, Virüsten Korkunca Konseri İptal Etti   SICAK
25                                                        Medine'de Mescid-i Nebi Yakınında İftar Saatinde Patmalama   SICAK
26                                                            Fenerbahçe, Gregory van der Wiel ile sözleşme imzaladı   SICAK
27                                                  Suudi Arabistan'da Düzenlenen Saldırılardan İlk Görüntüler Geldi   SICAK
28                                              Medine'deki patlamanın ardından olay yerinden ilk görüntüler / Video   SICAK
29                                                    NBA’de yılın transferi: Kevin Durant, Golden State Warriors’ta   SICAK
...                                                                                                              ...     ...
43736                                     ABD Adalet Bakanlığı yetkilileri, 'Trump'ın görevden alınmasını' t

In [0]:
df['Categories'].value_counts()

SICAK                    16889
GÜNDEM                   12983
DÜNYA                     9226
SPOR                      1967
GÜNDEM|SICAK              1135
DÜNYA|SICAK                458
SANAT                      285
DÜNYA|GÜNDEM               207
Teknoloji                  144
Video                      100
DÜNYA|SPOR                  76
DÜNYA|Teknoloji             73
SICAK|SPOR                  51
GÜNDEM|SPOR                 33
DÜNYA|SANAT                 27
SANAT|Video                 21
DÜNYA|Video                 20
GÜNDEM|SANAT                19
SPOR|Video                  17
GÜNDEM|Teknoloji            10
DÜNYA|GÜNDEM|SPOR            8
GÜNDEM|Video                 5
News                         3
DÜNYA|GÜNDEM|SICAK           3
SICAK|Teknoloji              1
SANAT|SICAK                  1
DÜNYA|GÜNDEM|SANAT           1
DÜNYA|Teknoloji|Video        1
SPOR|Teknoloji               1
SICAK|Video                  1
Name: Categories, dtype: int64

In [0]:
WPT = nltk.WordPunctTokenizer()
stop_word_list = nltk.corpus.stopwords.words('turkish')

def norm_doc(single_doc):
    # TR: Dokümandan belirlenen özel karakterleri ve sayıları at
    # EN: Remove special characters and numbers
    single_doc = re.sub(" \d+", " ", single_doc)
    pattern = r"[{}]".format(",.;") 
    single_doc = re.sub(pattern, "", single_doc) 
    # TR: Dokümanı küçük harflere çevir
    # EN: Convert document to lowercase
    single_doc = single_doc.lower()
    single_doc = single_doc.strip()
    # TR: Dokümanı token'larına ayır
    # EN: Tokenize documents
    tokens = WPT.tokenize(single_doc)
    # TR: Stop-word listesindeki kelimeler hariç al
    # EN: Filter out the stop-words 
    filtered_tokens = [token for token in tokens if token not in stop_word_list]
    # TR: Dokümanı tekrar oluştur
    # EN: Reconstruct the document
    single_doc = ' '.join(filtered_tokens)
    return single_doc

norm_docs = np.vectorize(norm_doc) #like magic :)
normalized_documents = norm_docs(docs)
print(normalized_documents)

['küba milli takımı oyuncularının bir kadına tecavüz ettiği i ̇ ddia edildi'
 "daily telegraph : ' suriyelilere vatandaşlık teklifi ab anlaşmasını tehlikeye atıyor '"
 "aym ' den ' yüksek sesli ezan ' şikayetine ret" ...
 "abd ' uyuyan gence altı polis birden ateş açtı"
 'coca cola hisseleri son yılın düşük seviyesinde'
 'kendisine saldıran dağ aslanını silah kullanmadan öldüren koşucu : ayağımla ensesine öyle bir bastırdım']


In [0]:
from sklearn.feature_extraction.text import CountVectorizer
BoW_Vector = CountVectorizer(min_df = 0., max_df = 1.)
BoW_Matrix = BoW_Vector.fit_transform(normalized_documents)
#print (BoW_Matrix)

# TR: BoW_Vector içerisindeki tüm öznitelikleri al
# EN: Fetch al features in BoW_Vector
features = BoW_Vector.get_feature_names()
print ("features[50]:" + features[46])
print ("features[52]:" +features[48])

BoW_Matrix = BoW_Matrix.toarray()
print(BoW_Matrix)
# TR: Doküman - öznitelik matrisini göster
# EN: Print document by term matrice
BoW_df = pd.DataFrame(BoW_Matrix, columns = features)
BoW_df
#print(BoW_df.info())

features[50]:140
features[52]:145
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


00  000  000tl  01  03  ...  şüpheyle  şık  şımardı  şımarık  şırnak
0       0    0      0   0   0  ...         0    0        0        0       0
1       0    0      0   0   0  ...         0    0        0        0       0
2       0    0      0   0   0  ...         0    0        0        0       0
3       0    0      0   0   0  ...         0    0        0        0       0
4       0    0      0   0   0  ...         0    0        0        0       0
5       0    0      0   0   0  ...         0    0        0        0       0
6       0    0      0   0   0  ...         0    0        0        0       0
7       0    0      0   0   0  ...         0    0        0        0       0
8       0    0      0   0   0  ...         0    0        0        0       0
9       0    0      0   0   0  ...         0    0        0        0       0
10      0    0      0   0   0  ...         0    0        0        0       0
11      0    0      0   0   0  ...         0    0        0        0       0
12      0    0      0   0   0  ...         0    0        0        0       0
13      0    0      0   0   0  ...         0    0        0        0       0
14      0    0      0   0   0  ...         0    0        0        0       0
15      0    0      0   0   0  ...         0    0        0        0       0
16      0    0      0   0   0  ...         0    0        0        0       0
17      0    0      0   0   0  ...         0    0        0        0       0
18      0    0      0   0   0  ...         0    0        0        0       0
19      0    0      0   0   0  ...         0    0        0        0       0
20      0    0      0   0   0  ...         0    0        0        0       0
21      0    0      0   0   0  ...         0    0        0        0       0
22      0    0      0   0   0  ...         0    0        0        0       0
23      0    0      0   0   0  ...         0    0        0        0       0
24      0    0      0   0   0  ...         0    0        0        0       0
25      0    0      0   0   0  ...         0    0        0        0       0
26      0    0      0   0   0  ...         0    0        0        0       0
27      0    0      0   0   0  ...         0    0        0        0       0
28      0    0      0   0   0  ...         0    0        0        0       0
29      0    0      0   0   0  ...         0    0        0        0       0
...    ..  ...    ...  ..  ..  ...       ...  ...      ...      ...     ...
43736   0    0      0   0   0  ...         0    0        0        0       0
43737   0    0      0   0   0  ...         0    0        0        0       0
43738   0    0      0   0   0  ...         0    0        0        0       0
43739   0    0      0   0   0  ...         0    0        0        0       0
43740   0    0      0   0   0  ...         0    0        0        0       0
43741   0    0      0   0   0  ...         0    0        0        0       0
43742   0    0      0   0   0  ...         0    0        0        0       0
43743   0    0      0   0   0  ...         0    0        0        0       0
43744   0    0      0   0   0  ...         0    0        0        0       0
43745   0    0      0   0   0  ...         0    0        0        0       0
43746   0    0      0   0   0  ...         0    0        0        0       0
43747   0    0      0   0   0  ...         0    0        0        0       0
43748   0    0      0   0   0  ...         0    0        0        0       0
43749   0    0      0   0   0  ...         0    0        0        0       0
43750   0    0      0   0   0  ...         0    0        0        0       0
43751   0    0      0   0   0  ...         0    0        0        0       0
43752   0    0      0   0   0  ...         0    0        0        0       0
43753   0    0      0   0   0  ...         0    0        0        0       0
43754   0    0      0   0   0  ...         0    0        0        0       0
43755   0    0      0   0   0  ...         0    0        0        0       0
43756   0    0      0   0   0  ...         0    0      

In [0]:
from sklearn.decomposition import LatentDirichletAllocation
number_of_topics = 20
BoW_Matrix = BoW_Vector.fit_transform(normalized_documents)
LDA = LatentDirichletAllocation(n_components = number_of_topics, 
                                max_iter = 10, 
                                learning_offset = 50.,
                                random_state = 0,
                                learning_method = 'online').fit(BoW_Matrix)
features = BoW_Vector.get_feature_names()
for t_id, topic in enumerate(LDA.components_):
    print ("Topic %d:" % (t_id))
    print (" ".join([features[i]
                    for i in topic.argsort()[:-number_of_topics - 1:-1]]))

Topic 0:
açıklaması srail un rus dan kaybetti hayatını afrin bakan yunanistan göre aday albayrak krizi ordusu emre savaşı of ekonomik önünde
Topic 1:
suudi kaşıkçı ta arabistan kadar ankara olarak operasyonu lk hava serbest temmuz dakika gül prens ün açıldı edildi cia nı
Topic 2:
stanbul başkanı rusya eski verdi nun savaş destek tehdit terör nato cinsel nedeniyle dlib belediye vurdu bankası merkel akar verildi
Topic 3:
den geldi fazla ali ilgili açıklama lira görüştü zmir gazze uyarı yüksek hindistan yüzünden üzerine birlikte tazminat adı olsun ölüm
Topic 4:
var son kılıçdaroğlu tl bulundu la olacak in twitter davasında su davası yılın deniz hakaret anlattı yanlış buldu ceo üniversitesi
Topic 5:
nin türkiye kişi geliyor tepki eden ahmet yı facebook tutuklandı koç suriyeli sert bedelli iddia açtı maduro gazeteci kar askerlik
Topic 6:
bin açıkladı yaptı geçti olabilir soylu yılmaz önce adayı nden adalet yapan brunson hollanda güneş iş ortak çişleri bana araç
Topic 7:
erdoğan dan cumhurba